### ISSUE TITLE
Plan upcoming major releases 

### ISSUE THREAD

**Issue by bmish** [square/eslint-plugin-square#567]
Breaking changes:

v26:
* Drop old Node versions
* Consider whether we should switch to a maintained fork of eslint-plugin-node? https://github.com/eslint-community/eslint-plugin-n
   * But this will be quite disruptive since consumers will have to update all their disable comments and custom config from `node/` to `n/`

v25:
* https://github.com/square/eslint-plugin-square/pull/838

v24:
* https://github.com/square/eslint-plugin-square/issues/697
* #705
* #827
* #829
* #815

v23:
* #675
* #676
* #692
* #681
* #691
* #674

v22:
* #588
* #586
* #587
  * #589
* Update any dependencies with major version updates:
  * #582
* Re-evaluate which eslint-plugin-unicorn rules we're disabling in `base` config 
* https://github.com/square/eslint-plugin-square/pull/565

Previous major release:
* https://github.com/square/eslint-plugin-square/releases/tag/v24.0.0 (Jan 12, 2023)
* https://github.com/square/eslint-plugin-square/releases/tag/v23.0.0 (Jul 27, 2022)
* https://github.com/square/eslint-plugin-square/releases/tag/v22.0.0 (Feb 17, 2022)
* https://github.com/square/eslint-plugin-square/releases/tag/v21.0.0 (Oct 21, 2021)

**Comment by maxbeatty** [comment]
re: Drop old Node versions - https://github.com/square/eslint-plugin-square/pull/886

**Comment by maxbeatty** [comment]
Broke out switching to eslint-plugin-n in #922 and will keep v26 focused on dropping Node.js support and getting pending dependency upgrades applied
