### ISSUE TITLE
Conflicting filename regex rules for React components

### ISSUE THREAD

**Issue by rachid-square** [square/eslint-plugin-square#659]
## Description

Extending `plugin:square/react` adds [an override](https://github.com/square/eslint-plugin-square/blob/b10c3c118c121ceb6d5fd422833f01c6c2b51da0/lib/config/react.js#L18-L23) to `src/components` which sets the following rule:

```
'filenames/match-regex': ['error', filenames.regex.pascal],
```

It also automatically extends the base config which applies a [conflicting rule](https://github.com/square/eslint-plugin-square/blob/b10c3c118c121ceb6d5fd422833f01c6c2b51da0/lib/config/base.js#L99):

```
// Filenames:
'filenames/match-exported': ['error', 'kebab'],
```
## Proposed Solution

Update the react override to also set `filenames/match-exported`. I can make a PR, but I wanted to open the issue up to discussion first.

**Edit**:

I also found out that the recommended unicorn ruleset is bringing in a `unicorn/filename-case` rule which is also set to `kebab`. We might want to disable that rule since it's covered by `filenames/match-exported`

**Comment by rachid-square** [comment]
Will do. I updated the issue description with another conflicting rule `unicorn/filename-case`.

**Comment by bmish** [comment]
PR welcome to fix this.
