### ISSUE TITLE
Discuss React conventions for future releases

### ISSUE THREAD

**Issue by rachid-block** [square/eslint-plugin-square#697]
## Description

I wanted to discuss the filename rules for the [React config](https://github.com/square/eslint-plugin-square/blob/6595093f6836fed4c23391935436bc654fa5acee/lib/config/react.js#L17). React [does not](https://reactjs.org/docs/faq-structure.html#is-there-a-recommended-way-to-structure-react-projects) have strong opinions on how to structure a project. The current `eslint-plugin-square` config rules change the filename conventions for files in `src/components`. This has two effects:

1. it causes the project to use a mix of kebab and pascal case filenames
2. it implies that components should go in `src/components`

For the first point, is there a good reason not to stick to the base `kebab` case throughout the project?

For the second point, I think there are a couple of paths to consider. On one hand I see the value of `eslint-plugin-square` enforcing a convention. On the other hand, my team has struggled with a large project that is organized by file type. This is exacerbated by the fact that our project is worked on by multiple independent teams. However that use case may not be indicative of the problems a normal React project faces at Block.

I personally lean towards one of React's suggested options: [grouping by features or routes](https://reactjs.org/docs/faq-structure.html#grouping-by-features-or-routes). This lets you group functions specific to a component near the component without having too much code in the component file. `eslint-plugin-square` would not be able to enforce this, because each project would have it's own features. This flexibility would allow teams of various sizes to decide how their independent projects should be organized.

## Additional Notes

1. I was curious about the use case for [this rule override](https://github.com/square/eslint-plugin-square/blob/1a91b8f839097c4a628f38958f3229d64a06688b/lib/config/react.js#L24-L27) in the React config. It targets `src/setupTests.*` which seems overly specific. Should that have a comment explaining its use?

2. Have we discussed using [eslint-plugin-react-hooks](https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks)?

**Comment by bmish** [comment]
CC: @ghaagsma @maxbeatty who have both worked on the `react` config and may have insights into why it's setup the way it is and whether it needs to be generalized further (or removed if not needed anymore).

**Comment by rachid-square** [comment]
I did previously mention removing the config, but I noticed that it's pulling in `eslint-plug-react` [here](https://github.com/square/eslint-plugin-square/blob/2b0ea43f06613d2798fbf6378495daa060fca916/lib/config/react.js#L6), so we don't want to get rid of that part.

**Comment by rachid-block** [comment]
Update on this issue. We have another issue (#824) that looks like it has better traction for getting the eslint-plugin-react-hooks into the eslint-plugin-square rules. As for the file management ideas, our team is going to experiment with a different set of rules than what is in eslint-plugin-square, and we'll report our experience to see if this should be adopted by other teams starting new React projects. Given this, @bmish , should we close this issue for now?

**Comment by bmish** [comment]
Fine to close this. Open to considering improvements related to file management at a later point.

**Comment by rachid-block** [comment]
Will reopen later after we have experimented with alternate conventions (hopefully with some suggested eslint rules to enforce those conventions 😁 )
