### ISSUE TITLE
Conflicting prettier configs for quotes

### ISSUE THREAD

**Issue by bmish** [square/eslint-plugin-square#798]
@square/prettier-config reverted to using the prettier default of double quotes in [v2.0.0](https://github.com/square/prettier-config/releases/tag/v2.0.0).

This conflicts with our configuration of prettier to use single quote:

https://github.com/square/eslint-plugin-square/blob/07c3e6fbe28e82a4b6d22979890d2ff1a6fb0015/lib/config/base.js#L100-L105

and 

https://github.com/square/eslint-plugin-square/blob/07c3e6fbe28e82a4b6d22979890d2ff1a6fb0015/lib/config/base.js#L77-L82

Having this conflict between our ESLint config of prettier and our non-ESLint config of prettier can cause confusion and problems as occurred here: https://github.com/bmish/eslint-doc-generator/pull/283#issuecomment-1328114862

I'm in favor of keeping single quotes to avoid churn, so I think we need to remove or override the setting for @square/prettier-config.

@maxbeatty

**Comment by maxbeatty** [comment]
easiest thing to do is pin to v1 of @square/prettier-config and keep using single quotes. the shared configs rarely ever change and are so minimal they should continue to work with prettier (🤞🏼). if something does come up, it wouldn't be too much trouble to maintain both majors similar to Node's strategy.
