### ISSUE TITLE
Update eslint-plugin-unicorn

### ISSUE THREAD

**Issue by qrabigail** [square/eslint-plugin-square#880]
Running into this issue in our repo: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2076

A simple bump from `^46.0.0` to `^46.0.1` is all we need

**Comment by maxbeatty** [comment]
This prerelease includes eslint-plugin-unicorn v47 which will hopefully fix your issue https://github.com/square/eslint-plugin-square/releases/tag/v26.0.0-0

```sh
npm install eslint-plugin-square@next
```

I'm going to try to coordinate more in #567 before making a full release

**Comment by bmish** [comment]
You'll also need to bump our eslint requirement to match: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/03d24e7de3a462cf111b38012c13a49134734b40/package.json#L96

**Comment by maxbeatty** [comment]
v48 of eslint-plugin-unicorn will be included in v26
