### ISSUE TITLE
Rule configuration error for typescript plugin

### ISSUE THREAD

**Issue by stephtaylor** [square/eslint-plugin-square#93]
I'm getting the following error when trying to use the square/typescript plugin. I think the config should be `warn`, but the comment [here](https://github.com/square/eslint-plugin-square/blob/master/lib/config/typescript.js#L48) makes me think otherwise. Is there something I should change on my end? Thanks!

```
Error: .eslintrc.js » plugin:square/typescript#overrides[1]:
	Configuration for rule "@typescript-eslint/no-unused-vars" is invalid:
	Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"warning"').
```

**Comment by bmish** [comment]
Definitely a bug on our side! Opened a fix.
